### ISSUE TITLE
Placeholders in text input fields don't show the placeholders that are configured in Pega

### ISSUE THREAD

**Issue by DigitalDreamNL** [pegasystems/react-sdk-components#258]
**Describe the bug**
Text input fields have a placeholder attribute which is displayed in the input field while it's empty. In Pega this placeholder attribute can be set on input fields. This works correctly in the Pega application (placeholder is shown in empty fields) but does not work for the React SDK Components. In these components the placeholders are hardcoded to empty string.

**To Reproduce**
1. Add a text input field to a view and configure a placeholder
2. Open the view using the SDK Portal or Embed
3. Placeholder is not visible

**Expected behavior**
Placeholder should be displayed while input field is empty.

**Screenshots**
N/A

 - Version 8.23

**Comment by tumms2021389** [comment]
Hi @DigitalDreamNL,

Thanks for reporting the issue related to placeholder in react-sdk-components, we will look into this issue and provide the fix asap.

Thanks,
Siva

**Comment by tumms2021389** [comment]
Your PR is now merged to master branch, we will release these changes as part next release of react-sdk-components npm package
